[tool.poetry]
name = "hu"
version = "1.0.0-alpha.0"
description = "Helpful utility software for open source programmers"
authors = ["Steve Holden <steve@holdenweb.com>"]

packages = [
    { include = "hu", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6 || ^3.7 || ^3.8"

[tool.poetry.dev-dependencies]
tox = "^3.20"
flake8 = "^3.8"
coverage = "^5.3"
pytest = "^6.0.2"
pytest-cov = "^2.10"

[build-system]
requires = ["poetry>=0.12", "setuptools", "wheel"]
build-backend = "poetry.masonry.api"
